### ISSUE TITLE
Under Construction GIF Missing from Homepage

### ISSUE THREAD

**Issue by spilth** [hellosylvee/hellosylvee.github.io#1]
There's a message on the homepage stating that the site is under construction but there is no animated GIF to visualize this information.

**Comment by hellosylvee** [comment]
:gasp: such an egregious error on my part. This issue must be fixed!

https://github.com/hellosylvee/hellosylvee.github.io/commit/0ecd19f860d5ad5b8f342fa3982ebe964e4c3f1d
